#!/usr/bin/env bash

# This script formats the disk and installs the base system.
# Run this first from the live usb.
#   curl https://raw.githubusercontent.com/devinereshan/auto_install_arch/master/base_install > base_install
#   chmod u+x base_install
#   ./base_install
#
# Then follow the instructions printed on screen to configure the system.

printf "\nBeginning disk preparation...\n"

timedatectl set-ntp true

# partition the disk
cat <<EOF | fdisk /dev/sda
o
n
p


+512M
n
p



w
EOF
partprobe

# Ensure necessary modules are loaded
modprobe dm-crypt
modprobe dm-mod

# Create encrypted partition
cryptsetup -y -v luksFormat -s 512 -h sha512 /dev/sda2
cryptsetup open /dev/sda2 cryptroot

# make filesystems
mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/mapper/cryptroot

# Mount the partitions
mount /dev/mapper/cryptroot /mnt

mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

# Install os
pacstrap /mnt base linux linux-firmware vim man-db man-pages texinfo

# create fstab
genfstab -U /mnt >> /mnt/etc/fstab

printf "\nFinished installing base system.\nFurther configuration still required.\nEnter the following to complete installation:\n\tarch-chroot /mnt\n\tcurl https://raw.githubusercontent.com/devinereshan/auto_install_arch/master/configure >> configure\n\tchmod u+x configure\n\t./configure\n\nThen follow the prompts on screen\n"

